#!/usr/bin/env bash

run/build TSA
mi build/main.mc -- $@ test/tsa/*.in
run/build SYNC
mi build/main.mc -- $@ test/sync/*.in
run/build CTRL
mi build/main.mc -- $@ test/ctrl/*.in
run/build CTRL_SYNC
mi build/main.mc -- $@ test/ctrl-sync/*.in
